capitals/game/urls.py
from django.urls import path
from . import views, controller


app_name = 'game'
urlpatterns = [
    path("", views.index, name="index"),
    path("country_pyt", views.country_pyt, name="country_pyt"),
    path("country_odp", views.country_odp, name="country_odp"),
    path("city_pyt", views.city_pyt, name="city_pyt"),
    path("city_odp", views.city_odp, name="city_odp"),
    path("save_history", views.save_history, name="save_history"),
    # path("zla_odp", views.zla_odp, name="zla_odp"),

    ]

capitals/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path("", views.index, name="index"),
    path("country_pyt", views.country_pyt, name="country_pyt"),
    path("country_odp", views.country_odp, name="country_odp"),
    path("city_pyt", views.city_pyt, name="city_pyt"),
    path("city_odp", views.city_odp, name="city_odp"),
    path("save_history", views.save_history, name="save_history"),
    # path("zla_odp", views.zla_odp, name="zla_odp"),

    ]

capitals/question/models.py
from django.db import models


class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

game/models.py
import datetime
from django.db import models
from django.utils import timezone



class Countries(models.Model):
    countries = models.CharField(max_length=45)

    def __str__(self):
        return f'{self.countries}'

    class Meta:
        managed = True
        db_table = 'countries'


class Cities(models.Model):
    countries = models.OneToOneField(Countries, on_delete=models.CASCADE, null=True)
    cities = models.CharField(max_length=45)

    def __str__(self):
        return f'{self.cities}'

    class Meta:
        managed = True
        db_table = 'cities'


class Cc(models.Model):
    country = models.CharField(max_length=45)
    city = models.CharField(max_length=45)

    def __str__(self):
        return f'{self.country} - {self.city}'

    class Meta:
        managed = True
        db_table = 'cc'


class AuthUser(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    def __str__(self):
        return f'{self.username}'
        # return f'{self.id} - {self.username}'

    class Meta:
        managed = False
        db_table = 'auth_user'



class History(models.Model):
    id = models.IntegerField(primary_key=True)
    question = models.CharField(max_length=100)
    correct_ans = models.CharField(max_length=100)
    username_id = models.ForeignKey(AuthUser, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.question} - {self.correct_ans} - {self.username_id}'

    class Meta:
        managed = True
        db_table = 'history'

game/controller.py
from django.http import HttpResponseRedirect

from .models import Cc, History, AuthUser



# controller

def save_answers_history(request):
    if request.methode == 'POST':
        q_id = request.POST.get('q_id')
        a_id = request.POST.get('a_id')



def glosowanie(request, wybor_id):
    wybor = Countries.objects.get(pk=wybor_id)
    wybor.votes += 1
    wybor.save()
    return HttpResponseRedirect("../oddano_glos")

game/views.py
from .models import Countries, Cities, Cc, History, AuthUser
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .controller import glosowanie
import random
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'game/index.html', {})


def country_pyt(request):

    total_nr_of_id = Cc.objects.count()
    random_id = random.randint(0, total_nr_of_id - 1)
    query = Cc.objects.values_list('country', 'city')[random_id]
    # alternatywna metoda losowania odp a
    # query = Cc.objects.values_list('country', 'city').order_by('?').first()

    city_for_country_pyt = query[1]
    country_odp_a = query[0]    # prawidlowa odpowiedz

    random_id = random.randint(0, total_nr_of_id - 1)
    country_odp_b = Cc.objects.values_list('country', 'city')[random_id][0]
    # alternatywna metoda losowania odp b
    # country_odp_b = Cc.objects.values_list('country', 'city').order_by('?').first()[0]

    random_id = random.randint(0, total_nr_of_id - 1)
    country_odp_c = Cc.objects.values_list('country', 'city')[random_id][0]
    # alternatywna metoda losowania odp c
    # country_odp_c = Cc.objects.values_list('country', 'city').order_by('?').first()[0]

    user_id = request.user.id

    lista_country_odp = [country_odp_a, country_odp_b, country_odp_c]
    random.shuffle(lista_country_odp)

    return render(request, "game/countries_pyt.html", {
        'city_for_country_pyt': city_for_country_pyt,
        'lista_country_odp': lista_country_odp,
        'user_id': user_id,
        'country_odp_a': country_odp_a,
    })

def country_odp(request):
    if request.method == 'POST':
        country_odp_a = request.POST.get('country_odp_a')
        city_for_country_pyt = request.POST.get('city_for_country_pyt')
        user_id = request.POST.get('user_id')

    return render(request, "game/countries_odp.html", {
        'city_for_country_pyt': city_for_country_pyt,
        'country_odp_a': country_odp_a,
        'user_id': user_id,
    })


def city_pyt(request):
    total_no_of_id = Cc.objects.count()
    random_id = random.randint(0, total_no_of_id - 1)
    query = Cc.objects.values_list('country', 'city')[random_id]

    # alternatywna metoda losowania odp a
    # query = Cc.objects.values_list('country', 'city').order_by('?').first()

    country_for_city_pyt = query[0]
    city_odp_a = query[1]    # prawidlowa odpowiedz


    random_id = random.randint(0, total_no_of_id - 1)
    city_odp_b = Cc.objects.values_list('country', 'city')[random_id][1]
    # alternatywna metoda losowania odp b
    # city_odp_b = Cc.objects.values_list('country', 'city').order_by('?').first()[1]


    random_id = random.randint(0, total_no_of_id - 1)
    city_odp_c = Cc.objects.values_list('country', 'city')[random_id][1]
    # alternatywna metoda losowania odp c
    # city_odp_c = Cc.objects.values_list('country', 'city').order_by('?').first()[1]

    user_id = request.user.id

    lista_city_odp = [city_odp_a, city_odp_b, city_odp_c]
    random.shuffle(lista_city_odp)

    return render(request, "game/cities_pyt.html", {
        'country_for_city_pyt': country_for_city_pyt,
        'lista_city_odp': lista_city_odp,
        'user_id': user_id,
        'city_odp_a': city_odp_a,
    })


def city_odp(request):
    if request.method == 'POST':
        city_odp_a = request.POST.get('city_odp_a')
        country_for_city_pyt = request.POST.get('country_for_city_pyt')
        user_id = request.POST.get('user_id')
    return render(request, "game/cities_odp.html", {
        'country_for_city_pyt': country_for_city_pyt,
        'city_odp_a': city_odp_a,
        'user_id': user_id,
    })


@login_required
def save_history(request):
    if request.method == 'POST':
        question = request.POST.get('question')
        correct_ans = request.POST.get('correct_ans')

        user_id = request.user.id
        # zapisanie wynikow do bazy danych
        history = History(question=question, correct_ans=correct_ans, username_id_id=user_id)
        history.save()
        # wyswietlanie ostatnich (10) pytanie + odpowiedz + uzytkownik
        last_items = History.objects.order_by('-id')[:10]

        return render(request, 'save_history.html', {
            'question': question,
            'correct_ans': correct_ans,
            'user_id': user_id,
            'last_items': last_items,
        })




# def get_last_five_history_items(request, user):
#     last_five_items = History.objects.filter(username_id_id=user).order_by('-timestamp')[:5]
#     return render(request, 'save_history.html', {
#         # 'question': question,
#         # 'correct_ans': correct_ans,
#         # 'user_id': user_id,
#         # 'last_hist': last_hist,
#         'last_five_items': last_five_items,
#     })

    # return last_five_items


# def zla_odp(request):
#     return HttpResponse('To nie jest poprawna odpowiedź! Spróbuj ponownie!')



# def ankieta(request, question_id):
#     if request.method == "POST":
#         nr_odp = request.POST.get("nr_odp")
#         return glosowanie(request, nr_odp)
#     try:
#         return render(request, "game/ankieta.html", {
#             'pytanie': Questions.objects.get(pk=question_id),
#         })
#     except Questions.DoesNotExist:
#         return HttpResponse('Nie ma takiego pytania')


# Powiązanie dwoch tabel Cities i Countries - zrobione w shellu

# for ci in Cities:
#     city = Cities.objects.create(nazwa=f"City {ci}")
#     country = Countries.objects.create(nazwa=f"Country {ci}")
#     city.country = country
#     city.save()

# stworzenie połączenia pomiedzy dwoma istniejacymi modelami (tabelami)
# w ktorych sa juz wprowadzone dane
# def relation_creation():
#     for ci in Cities.objects.all():
#         ci.countries_id = ci.id
#         ci.save()

game/templates/game/ankieta.html
<b>Pytanie:</b> {{ pytanie.question_text }}
Wybierz swoja odpowiedz:
<ul>
   {% for odpowiedz in pytanie.choice_set.all %}
        <li><a href="{% url 'glosowanie' odpowiedz.id %}">Zaglosuj na: {{ odpowiedz.choice_text }}</a></li>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="nr_odp" value="{{ odpowiedz.id }}">
        <button name="foo" value="upvote">zaglosuj na</button>
    </form>
      {% endfor %}
</ul>

game/templates/game/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

game/templates/game/cities_odp.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button><br>


<span style="color: white">
    <span style="font-size:x-large">
        <a>Stolicą {{ country_for_city_pyt }} jest {{ city_odp_a }}</a>
    </span>
</span>

<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">
        </span>
    </span>
</ul><br>

<form method="post" action="{% url 'game:save_history' %}">
    {% csrf_token %}
    <input type="hidden" name="question" id="question" value="{{ city_odp_a }}">
    <input type="hidden" name="correct_ans" id="correct_ans" value="{{ country_for_city_pyt }}">
    <input type="hidden" name="user_id" id="user_id" value="{{ user_id }}">
    <button style="margin-bottom:30px; position: absolute; top: 140px; left: 48px"
            name="foo"
            value="save"><font
            size="4">Zapisz odpowiedź</font></button>
</form>
<br>

<ul>
<button style="margin-bottom:30px; margin-top:10px; " type="button">
    <a href="{% url 'game:city_pyt' %}"><font size="4">Kolejne pytanie</font></a>
</button>
</ul>
<ul>
<button type="button">
    <a href="{% url 'game:index' %}"><font size="4">Wybierz rodzaj pytania</font></a>
</button>
</ul>

game/templates/game/cities_pyt.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button><br>


<span style="color: white">
    <span style="font-size:x-large">
        <a>Jak nazywa się stolica {{ country_for_city_pyt }}?</a>
    </span>
</span>

<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">

    {% for city in lista_city_odp %}
        <li><a href="{% url 'game:city_odp' %}">{{ city }}</a></li>
    {% endfor %}

        </span>
    </span>
</ul>
<br>
<ul>
<br>
    <form method="post" action="{% url 'game:city_odp' %}">
    {% csrf_token %}
    <input type="hidden" name="city_odp_a" id="city_odp_a" value="{{ city_odp_a }}">
    <input type="hidden" name="country_for_city_pyt" id="country_for_city_pyt" value="{{ country_for_city_pyt }}">
    <input type="hidden" name="user_id" id="user_id" value="{{ user_id }}">
    <button style="margin-bottom:30px; position: absolute; top: 250px; left: 48px"
            name="foo"
            value="save"><font size="4">Pokaż odpowiedź</font></button>
</form>
</ul>

<ul>
<button type="button">
    <a href="{% url 'game:index' %}"><font size="4">Wybierz rodzaj pytania</font></a>
</button>
</ul>

game/templates/game/countries_odp.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button><br>


<span style="color: white">
    <span style="font-size:x-large">
        <a>{{ city_for_country_pyt }} jest stolicą {{ country_odp_a }}</a>
    </span>
</span>

<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">
        </span>
    </span>
</ul><br>

<form method="post" action="{% url 'game:save_history' %}">
    {% csrf_token %}
    <input type="hidden" name="question" id="question" value="{{ country_odp_a }}">
    <input type="hidden" name="correct_ans" id="correct_ans" value="{{ city_for_country_pyt }}">
    <input type="hidden" name="user_id" id="user_id" value="{{ user_id }}">
    <button style="margin-bottom:30px; position: absolute; top: 140px; left: 48px"
            name="foo"
            value="save"><font size="4">Zapisz odpowiedź</font></button>
</form>
<br>

<ul>
<button style="margin-bottom:30px; margin-top:10px; " type="button">
    <a href="{% url 'game:country_pyt' %}"><font size="4">Kolejne pytanie</font></a>
</button>
</ul>
<ul>
<button type="button">
    <a href="{% url 'game:index' %}"><font size="4">Wybierz rodzaj pytania</font></a>
</button>
</ul>

game/templates/game/countries_pyt.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button><br>


<span style="color: white">
    <span style="font-size:x-large">
        <a>Jak nazywa się kraj którego stolicą jest {{ city_for_country_pyt }}?</a>
    </span>
</span>

<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">

    {% for country in lista_country_odp %}
        <li><a href="{% url 'game:country_odp' %}">{{ country }}</a></li>
    {% endfor %}

        </span>
    </span>
</ul>
<br>
<ul>
<br>
    <form method="post" action="{% url 'game:country_odp' %}">
    {% csrf_token %}
    <input type="hidden" name="country_odp_a" id="question" value="{{ country_odp_a }}">
    <input type="hidden" name="city_for_country_pyt" id="correct_ans" value="{{ city_for_country_pyt }}">
    <input type="hidden" name="user_id" id="user_id" value="{{ user_id }}">
    <button style="margin-bottom:30px; position: absolute; top: 250px; left: 48px"
            name="foo"
            value="save"><font size="4">Pokaż odpowiedź</font></button>
</form>
</ul>

<ul>
<button type="button">
    <a href="{% url 'game:index' %}"><font size="4">Wybierz rodzaj pytania</font></a>
</button>
</ul>

game/templates/game/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}" xmlns="http://www.w3.org/1999/html">
<span style="color: white">
    <span style="font-size:x-large">

{% if user.is_authenticated %}
  Hi {{ user.username }}!
<br>
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'game:index' %}"><font size="4">Start Your Quiz Game!</font></a>
</button><br>

<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button>

{% else %}
 <h2><p>You are not logged in</p></h2>

<button style="margin-bottom:30px;" type="button">
<a href="{% url 'login' %}"><font size="4">Log In</font></a>
</button>
<br>or</br>
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'signup' %}"><font size="4">Sign Up</font></a>
</button>

{% endif %}
{% endblock %}

  </span>
</span>

game/templates/game/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button>


<span style="color: white">
    <span style="font-size: xx-large">
        <br><b>Cześć {{ user.username }}!</b></br>
        <br>
        Wybierz rodzaj pytania:
    </span>
</span>


<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">
            <li><a href="{% url 'game:country_pyt' %}">Jak nazywa się kraj którego stolicą jest...?</a></li>
            <li><a href="{% url 'game:city_pyt' %}">Jak nazywa się stolica...?</a></li>
        </span>
    </span>
</ul>

game/templates/game/save_history.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">
<br>
<button style="margin-bottom:30px;" type="button">
<a href="{% url 'logout' %}"><font size="4">Log Out</font></a>
</button><br>


<span style="color: white">
    <span style="font-size:x-large">
        <a>Pytanie i odpowiedź zostały zapisane</a><br>
        <br><a>Historia ostatnich 10 pytań i odpowiedzi</a>

<ul type="square">
    <span style="color: white">
        <span style="font-size:large">
            {% for item in last_items %}
            <li>{{ item }}</li>
            {% endfor %}
        </span>
    </span>
</ul>

    </span>
</span>

<ul type="square">
    <span style="color: white">
        <span style="font-size:x-large">
        </span>
    </span>
</ul>

<ul>
<button style="margin-bottom:30px;" type="button">
    <a href="{% url 'game:country_pyt' %}"><font size="4">Kolejne pytanie</font></a>
</button>
</ul>
<ul>
<button type="button">
    <a href="{% url 'game:index' %}"><font size="4">Wybierz rodzaj pytania</font></a>
</button>
</ul>